# DATABASE
DB_URL=jdbc:mysql://interchange.proxy.rlwy.net:38550/railway?useSSL=false&serverTimezone=Asia/Ho_Chi_Minh&allowPublicKeyRetrieval=true
DB_USERNAME=root
DB_PASSWORD=SZhkpiaBKssdXIyGLhTxbLQzGVlOnZBD

# JWT
JWT_SECRET=YOUR_JWT_SECRET

# EMAIL
MAIL_USERNAME=YOUR_EMAIL@gmail.com
MAIL_PASSWORD=YOUR_APP_PASSWORD

# GOOGLE OAUTH2
GOOGLE_CLIENT_ID=YOUR_GOOGLE_CLIENT_ID
GOOGLE_CLIENT_SECRET=YOUR_GOOGLE_CLIENT_SECRET

# FRONTEND
FRONTEND_URL=http://localhost:3000
APP_CORS_ALLOWED_ORIGINS=http://localhost:3000

# VNPAY
VNPAY_TMN_CODE=YOUR_VNPAY_TMN_CODE
VNPAY_HASH_SECRET=YOUR_VNPAY_HASH_SECRET
VNPAY_PAY_URL=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
VNPAY_RETURN_URL=http://localhost:3000/payments/vnpay/return

# GEMINI AI (optional)
GEMINI_API_KEY=
